### ISSUE TITLE
MessageAttributes support

### ISSUE THREAD

**Issue by leemhenson** [Comcast/cmb#32]
It looks to me like cmb doesn't support custom MessageAttributes in addition to the normal Attributes (SentTimestamp etc). Is this planned? 

See:
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_Message.html
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
http://docs.aws.amazon.com/sns/latest/api/API_Publish.html

**Comment by leemhenson** [comment]
Looks like this is on master now? I'm going to give it a whirl. :snowboarder:

**Comment by boriwo** [comment]
Yes, this feature is experimental and not completed yet. Basic attributes (string, number, binary) may work in cqs already but there's no bridge from cns to cqs yet. Will update here, when it makes sense to try.

**Comment by boriwo** [comment]
Just checked in the cns part. You can give it a try now. Note that I had to change your ruby script slightly to make it work.

**Comment by leemhenson** [comment]
:cake: yeah looks good, thanks!
